### 1. Array Creation and Basic Operations
1. **Create a 1D array of the first 10 positive integers.**
   - Print the array.
   - Find the sum of all elements in the array.
   - Calculate the mean of the elements.

2. **Create a 2D array of shape (3, 4) with random integers between 1 and 10.**
   - Print the array.
   - Find the maximum and minimum values in the array.
   - Calculate the sum of each row and each column.

### 2. Array Indexing and Slicing
3. **Create a 1D array of 20 random integers between 1 and 100.**
   - Print the array.
   - Print the elements from index 5 to 15.
   - Print every second element of the array.

4. **Create a 2D array of shape (5, 5) with random integers between 1 and 50.**
   - Print the array.
   - Extract and print the second row.
   - Extract and print the third column.
   - Extract and print a 3x3 subarray from the original array.

### 3. Array Manipulation
5. **Create two 1D arrays of 10 random integers each.**
   - Concatenate the two arrays.
   - Sort the concatenated array.
   - Find the unique elements in the concatenated array.

6. **Create a 2D array of shape (4, 4) with random integers between 1 and 20.**
   - Print the array.
   - Flatten the array into a 1D array.
   - Reshape the flattened array back into a 2D array of shape (2, 8).

### 4. Mathematical and Statistical Operations
7. **Create a 1D array of 15 random integers between 1 and 50.**
   - Print the array.
   - Calculate and print the standard deviation of the array.
   - Find and print the index of the maximum value in the array.
   - Normalize the array (scale the values to a range between 0 and 1).

8. **Create two 2D arrays of shape (3, 3) with random integers between 1 and 10.**
   - Print both arrays.
   - Perform element-wise addition, subtraction, and multiplication of the arrays.
   - Calculate the dot product of the arrays.


In [2]:
 import numpy as np

 #1. create a 1D array pf the first 10 positive integers
 array = np.arange(1,11)

 # print the array
 print("Array:", array)

 #2. Find the sum of all elementsin the array
 array_sum = np.sum(array)
 print("sum of all elements:", array_sum)

 #3. calculate the mean of the elements
 array_mean = np.mean(array)
 print("Mean of the elements:", array_mean)

Array: [ 1  2  3  4  5  6  7  8  9 10]
sum of all elements: 55
Mean of the elements: 5.5


In [3]:
# 2D array with random integers between 1 and 10
array_2d = np.random.randint(1, 11, size=(3, 4))
print("2D array:\n", array_2d)

# Maximum and minimum values
max_value = np.max(array_2d)
min_value = np.min(array_2d)
print("Maximum value:", max_value)
print("Minimum value:", min_value)

# sum of each row and each column
sum_rows = np.sum(array_2d, axis=1)
sum_columns = np.sum(array_2d, axis=0)
print("sum of each row:", sum_rows)
print("sum of each column:", sum_columns)

2D array:
 [[9 5 9 7]
 [7 8 5 5]
 [2 9 7 9]]
Maximum value: 9
Minimum value: 2
sum of each row: [30 25 27]
sum of each column: [18 22 21 21]


In [4]:
# 1D array of 20 random integers between 1 and 100
array_20 = np.random.randint(1, 101, size=20)
print("1D array of 20 random integers:", array_20)

# Elements from index 5 to 15
print("Elements from index 5 to 15:", array_20[5:16])

# Every second element
print("Every second element:", array_20[::2])

1D array of 20 random integers: [75 25 60 50 89 60  2 99 21  3 66  4 89 78 43 55 17 34 10 76]
Elements from index 5 to 15: [60  2 99 21  3 66  4 89 78 43 55]
Every second element: [75 60 89  2 21 66 89 43 17 10]


In [5]:
# 2D array of shape (5, 5) with random integers between 1 and 50
array_5x5 = np.random.randint(1, 51, size=(5, 5))
print("2D array:\n", array_5x5)

# Extract and print the second row
second_row = array_5x5[1, :]
print("second row:", second_row)

# Extract and print the third column
third_column = array_5x5[:, 2]
print("Third column:", third_column)

# Extract and print a 3x3 subarray
subarray_3x3 = array_5x5[1:4, 1:4]
print("3x3 subarray:\n", subarray_3x3)

2D array:
 [[18 10 50 25  7]
 [29 47  2  3 17]
 [35 22 18  3 16]
 [22  3 23 44  2]
 [46  6 15 19  8]]
second row: [29 47  2  3 17]
Third column: [50  2 18 23 15]
3x3 subarray:
 [[47  2  3]
 [22 18  3]
 [ 3 23 44]]


In [6]:
# Two 1D arrays of 10 random integers each
array1 = np.random.randint(1, 101, size=10)
array2 = np.random.randint(1, 101, size=10)
print("Array 1:", array1)
print("Array 2:", array2)

# concentrate the two arrays
concatenated_array = np.concatenate((array1, array2))
print("concatenated array:", concatenated_array)

# sort the concatenated array
sorted_array = np.sort(concatenated_array)
print("sorted array:", sorted_array)

# unique elements
unique_elements = np.unique(sorted_array)
print("unique elements:", unique_elements)

Array 1: [27 93 67  6 55  8 41 57 37 46]
Array 2: [ 78 100  26  46  34  57  95   4   4  64]
concatenated array: [ 27  93  67   6  55   8  41  57  37  46  78 100  26  46  34  57  95   4
   4  64]
sorted array: [  4   4   6   8  26  27  34  37  41  46  46  55  57  57  64  67  78  93
  95 100]
unique elements: [  4   6   8  26  27  34  37  41  46  55  57  64  67  78  93  95 100]


In [7]:
# 2D array of shape(4, 4) with random integers between 1 and 20
array_4x4 = np.random.randint(1, 21, size=(4, 4))
print("2D array:\n", array_4x4)

# Flatten the array into a 1D array
flattened_array = array_4x4.flatten()
print("Flattened array:", flattened_array)

# Reshape the fattened array back into a 2D array of shape(2, 8)
reshaped_array = flattened_array.reshape((2, 8))
print("Reshaped array:\n", reshaped_array)

2D array:
 [[ 3 12 10 14]
 [17  1 20 19]
 [19  4 14 14]
 [ 5  2  3 11]]
Flattened array: [ 3 12 10 14 17  1 20 19 19  4 14 14  5  2  3 11]
Reshaped array:
 [[ 3 12 10 14 17  1 20 19]
 [19  4 14 14  5  2  3 11]]


In [8]:
# 1D array of 15 random integers between 1 and 50
array_15 = np.random.randint(1, 51, size=15)
print("1D array:", array_15)

# standard deviation
std_dev = np.std(array_15)
print("standard deviation:", std_dev)

# index of the maximum value
max_index = np.argmax(array_15)
print("Index of maximum value:", max_index)

# Normalize the array
normalized_array = (array_15 - np.min(array_15)) / (np.max(array_15) - np.min(array_15))
print("Normalized array:", normalized_array)

1D array: [38 37 12 35 50 12 46 50 37 42 50  5 17 21 27]
standard deviation: 14.748860596293154
Index of maximum value: 4
Normalized array: [0.73333333 0.71111111 0.15555556 0.66666667 1.         0.15555556
 0.91111111 1.         0.71111111 0.82222222 1.         0.
 0.26666667 0.35555556 0.48888889]


In [9]:
# Two 2D arrays of shape (3, 3) with random integers between 1 and 10
array_3x3_1 = np.random.randint(1, 11, size=(3, 3))
array_3x3_2 = np.random.randint(1, 11, size=(3, 3))
print("Array 1:\n", array_3x3_1)
print("Array 2:\n", array_3x3_2)

# Element -wise addition, subtraction, and multiplication
addition = array_3x3_1 + array_3x3_2
subtraction = array_3x3_1 - array_3x3_2
multiplication = array_3x3_1 * array_3x3_2
print("Element-wise addition:\n", addition)
print("Element-wise subtraction:\n", subtraction)
print("Element-wise multiplication:\n", multiplication)

# Dot product of the arrays
dot_product = np.dot(array_3x3_1, array_3x3_2)
print("Dot product:\n", dot_product)


Array 1:
 [[1 7 9]
 [1 8 7]
 [8 9 5]]
Array 2:
 [[1 5 7]
 [1 2 9]
 [6 3 4]]
Element-wise addition:
 [[ 2 12 16]
 [ 2 10 16]
 [14 12  9]]
Element-wise subtraction:
 [[ 0  2  2]
 [ 0  6 -2]
 [ 2  6  1]]
Element-wise multiplication:
 [[ 1 35 63]
 [ 1 16 63]
 [48 27 20]]
Dot product:
 [[ 62  46 106]
 [ 51  42 107]
 [ 47  73 157]]
