In [8]:
a=[1,2,3,4,5]
print(a)

[1, 2, 3, 4, 5]


In [10]:
### Load in Numpy (Import Numpy package)
import numpy as np
np_a = np.array(a)

In [12]:
print(type(a))

<class 'list'>


In [14]:
a = [1, 2, 3, 4, 5]
np_a = np.array(a)
print(np_a)

[1 2 3 4 5]


In [16]:
a = [1, 2, 3, 4, 5]
np_a = np.array(a)
print(type(np_a))
print(type(np_a))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [11]:
L = range(1000)
%timeit [i**2 for i in L]

91.4 µs ± 1.44 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [18]:
a = np.arange(1000)
%timeit a**2

2.48 µs ± 334 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [20]:
#1-D
a = np.array([0, 1, 2, 3])
a

array([0, 1, 2, 3])

In [22]:
#print dimensions
a.ndim

1

In [24]:
#shape
a.shape

(4,)

In [26]:
# 2-D
b = np.array([[0, 1, 2], [3, 4, 5]])
b

array([[0, 1, 2],
       [3, 4, 5]])

In [28]:
b.ndim

2

In [30]:
b.shape

(2, 3)

In [36]:
#3D
c = np.array([[[0, 1], [2, 3]], [[4, 5], [6,7]]])
c

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [38]:
c.ndim

3

In [40]:
c.shape

(2, 2, 2)

In [48]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [50]:
np.array(my_list)

array([1, 2, 3])

In [52]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [54]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [56]:
np.array(my_matrix).shape

(3, 3)

In [58]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [60]:
b = np.arange(1, 10, 2)
b

array([1, 3, 5, 7, 9])

In [62]:
a = np.linspace(0, 5, 6)
a

array([0., 1., 2., 3., 4., 5.])

In [64]:
np.linspace(0,10, 7)

array([ 0.        ,  1.66666667,  3.33333333,  5.        ,  6.66666667,
        8.33333333, 10.        ])

In [66]:
np.zeros(3)

array([0., 0., 0.])

In [112]:
b = np.zeros((2,2))
b

array([[0., 0.],
       [0., 0.]])

In [118]:
c = np.eye(3)
c

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [70]:
a = np.ones((4,3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [76]:
d = np.eye(3,2)
d

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [82]:
a = np.diag([7, 9, 3, 4])
a

array([[7, 0, 0, 0],
       [0, 9, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [84]:
np.diag(a)

array([7, 9, 3, 4])

In [86]:
random_array = np.random.randint(1,121,5)
print(random_array)

[ 41 118  51  53  93]


In [88]:
a = np.random.rand(4)
a

array([0.21532615, 0.14392088, 0.04289806, 0.57720407])

In [90]:
a = np.random.randn(100)
a

array([ 0.76333829, -0.05141609, -0.81291715, -0.16251979, -2.13103781,
       -0.8199708 , -1.29021771, -0.23944297, -2.10938564,  0.18517738,
        2.02719546,  0.26937173,  0.53034174,  1.47934853,  1.77374234,
        0.52104538, -1.03270592, -0.94292509, -0.58515407, -0.43174749,
       -0.1237061 , -0.11256439, -0.33362835, -0.1232557 , -0.75375202,
       -1.40329344, -0.64449432,  0.710833  , -0.63416516,  2.37262073,
        0.83223895, -0.56804056, -1.51585454, -0.57074046, -0.90520499,
       -0.84283148, -1.19394742, -0.98067855,  1.17340113, -1.44566309,
        1.6547935 , -1.0915544 ,  0.30619233,  1.91308278,  0.23239201,
       -0.2279165 , -0.51516299,  0.15261043,  0.09664573,  0.44239661,
        1.8269317 , -0.24381697, -0.74669507, -0.850234  , -0.61621353,
       -1.30837099,  0.42442504, -0.79099398,  0.62189997, -1.05165467,
       -2.00550925, -0.27238617, -0.13565055, -0.87073963,  0.20337595,
        1.16212918,  0.66507408,  0.73650287,  1.14601613, -0.91

In [92]:
a = np.array([1,2,3])
b = a
b[0] = 100
print(a)
print(b)

[100   2   3]
[100   2   3]


In [94]:
arr = np.arange(25)
print(arr)
print(arr.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
(25,)


In [96]:
a1=arr.reshape(5,5)
a1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [98]:
a = np.array([[1,2,3],[4,5,6]])
print(a)
print("shape of a: {}".format(a.shape))

[[1 2 3]
 [4 5 6]]
shape of a: (2, 3)


In [100]:
b = a.reshape(3,2)
print(b)
print("shape of b: {}".format(b.shape))

[[1 2]
 [3 4]
 [5 6]]
shape of b: (3, 2)


In [102]:
a = np.array([[1,2,3],[4,5,6]])
print("shape: {}".format(a.shape))
print(a)

shape: (2, 3)
[[1 2 3]
 [4 5 6]]


In [104]:
c = a.T
print(c)

[[1 4]
 [2 5]
 [3 6]]


In [106]:
a = np.array([[1, 2, 3], [4, 5, 6]])
a.ravel()


array([1, 2, 3, 4, 5, 6])

In [108]:
c.ravel()

array([1, 4, 2, 5, 3, 6])

In [120]:
a = np.array([[5, 4, 5], [2, 8, 2]])
b = np.sort(a, axis=1)
b

array([[4, 5, 5],
       [2, 2, 8]])

In [122]:
a = np.array([4,7,8])
a = np.append(a,[2,4,5])
print('Numpy array after addition:',a)

Numpy array after addition: [4 7 8 2 4 5]


In [124]:
a = np.delete(a,2)
print('Numpy array after deletion of one element:' ,a)

Numpy array after deletion of one element: [4 7 2 4 5]


In [126]:
a = np.arange(3,10)
print(a)
print(a[5])

[3 4 5 6 7 8 9]
8


In [128]:
a = np.diag([1, 2, 3])
print(a)
print(a[2,1])

[[1 0 0]
 [0 2 0]
 [0 0 3]]
0


In [130]:
a[2,1] = 5
a

array([[1, 0, 0],
       [0, 2, 0],
       [0, 5, 3]])

In [132]:
a = np.arange(4,18)
a

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17])

In [134]:
a[1:8:2]

array([ 5,  7,  9, 11])

In [136]:
a = np.arange(10)
a[5:]

array([5, 6, 7, 8, 9])

In [138]:
a[5:] = 10
a

array([ 0,  1,  2,  3,  4, 10, 10, 10, 10, 10])

In [140]:
b = np.arange(5)
b

array([0, 1, 2, 3, 4])

In [142]:
b[::-1]

array([4, 3, 2, 1, 0])

In [144]:
a[5:]=b[::-1]

In [146]:
a

array([0, 1, 2, 3, 4, 4, 3, 2, 1, 0])

In [148]:
a = np.random.randint(0, 20, 5)
a

array([16, 12, 14,  2,  9])

In [150]:
a[a % 2 == 0]

array([16, 12, 14,  2])

In [152]:
a[a % 2 == 0] = -1
a

array([-1, -1, -1, -1,  9])

In [154]:
a = np.arange(0, 101, 10)
a

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [156]:
a[[2, 3, 2, 4, 2]]

array([20, 30, 20, 40, 20])

In [160]:
a[[9, 7]] = -2000
a

array([    0,    10,    20,    30,    40,    50,    60, -2000,    80,
       -2000,   100])

In [162]:
a = np.array([1, 2, 3, 4])
print(a)
print(a+1)

[1 2 3 4]
[2 3 4 5]


In [164]:
a ** 2

array([ 1,  4,  9, 16])

In [166]:
b = np.ones(4) + 1
b

array([2., 2., 2., 2.])

In [168]:
a - b

array([-1.,  0.,  1.,  2.])

In [170]:
a * b

array([2., 4., 6., 8.])

In [174]:
a = np.array([[1,2],[3,4],[5,6]])
b = np.array([[4,4],[4,4],[4,4]])
print('sum of a and b :\n', a+b)

sum of a and b :
 [[ 5  6]
 [ 7  8]
 [ 9 10]]


In [176]:
print('product of a and b :\n',a*b)

product of a and b :
 [[ 4  8]
 [12 16]
 [20 24]]


In [178]:
c = np.diag([1, 2, 3, 4])
print(c * c)

[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]


In [180]:
a = np.array([[1,2,1],[3,4,3],[5,6,5]])
b = np.array([[4,4,1],[4,4,2],[4,4,3]])
print('Matrix multiplication:\n',np.matmul(a,b))

Matrix multiplication:
 [[16 16  8]
 [40 40 20]
 [64 64 32]]


In [182]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 2, 2, 4])
a == b

array([False,  True, False,  True])

In [184]:
a > b

array([False, False,  True, False])

In [186]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 2, 2, 4])
c = np.array([1, 2, 3, 4])

In [188]:
np.array_equal(a, c)

True

In [190]:
a = np.array([1, 1, 0, 0], dtype=bool)
b = np.array([1, 0, 1, 0], dtype=bool)

np.logical_or(a, b)

array([ True,  True,  True, False])

In [192]:
np.logical_and(a, b)

array([ True, False, False, False])

In [194]:
a = np.arange(5)
np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [196]:
np.log(a)

C:\Users\parth\AppData\Local\Temp\ipykernel_9272\176755284.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(a)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436])

In [198]:
np.exp(a)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [200]:
a = np.arange(4)
a + np.array([1, 2])

ValueError: operands could not be broadcast together with shapes (4,) (2,) 

In [202]:
x = np.array([1, 2, 3, 4])
np.sum(x)

10

In [204]:
x = np.array([[1, 1], [2, 2]])
x

array([[1, 1],
       [2, 2]])

In [206]:
x.sum(axis=0)

array([3, 3])

In [208]:
x.sum(axis=1)

array([2, 4])

In [210]:
x = np.array([1, 3, 2])
x.min()

1

In [212]:
x.max()

3

In [214]:
x.argmin()

0

In [216]:
x.argmax()

1

In [218]:
normal_array = np.arange(0,10,1)
print('Array is ',format(normal_array))

print('min element is',np.min(normal_array))

print('max element is ',np.max(normal_array))

print('sum of elements in array is ',np.sum(normal_array))

print('mean of elements in array is ',np.mean(normal_array))

print('median of elements in array is ',np.median(normal_array))

print('standard deviation of elements in array is ',np.std(normal_array))

Array is  [0 1 2 3 4 5 6 7 8 9]
min element is 0
max element is  9
sum of elements in array is  45
mean of elements in array is  4.5
median of elements in array is  4.5
standard deviation of elements in array is  2.8722813232690143
